import {CATALOG} from './catalog.js';
import {initializeApp} from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-app.js';
import {getAuth,onAuthStateChanged,signInWithEmailAndPassword,createUserWithEmailAndPassword,updateProfile,signOut} from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js';
import {initializeFirestore,getFirestore,persistentLocalCache,persistentMultipleTabManager,doc,getDoc,setDoc,writeBatch,onSnapshot,serverTimestamp,increment} from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js';
const VERSION='7.0.1';const firebaseConfig={apiKey:'AIzaSyCETXStRJ9xFhf93NwkQTHZIKGiIV230y8',authDomain:'nuestro-espacio-d7132.firebaseapp.com',projectId:'nuestro-espacio-d7132',storageBucket:'nuestro-espacio-d7132.firebasestorage.app',messagingSenderId:'294993809967',appId:'1:294993809967:web:6ef43d122d4947aa2cacda'};
const fb=initializeApp(firebaseConfig),auth=getAuth(fb);let db;try{db=initializeFirestore(fb,{localCache:persistentLocalCache({tabManager:persistentMultipleTabManager()})})}catch(error){console.warn('Persistencia avanzada no disponible; usando Firestore estándar.',error);db=getFirestore(fb)}
const $=id=>document.getElementById(id),num=v=>Number(v)||0,money=v=>'S/ '+num(v).toFixed(2),uid=()=>crypto.randomUUID?.()||Date.now()+'_'+Math.random().toString(36).slice(2),today=()=>new Date().toISOString().slice(0,10),norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
const defaults={shopping:[],tasks:[],expenses:[],notes:[],pantry:[],events:[],fixedExpenses:[],extraIncomes:[],customCatalog:[],favorites:[],priceHistory:[],budget:300,preferredStore:'market',theme:'light',salaryPayments:[{id:'q1',name:'Quincena',amount:500,day:15,active:true},{id:'q2',name:'Fin de mes',amount:900,day:31,active:true}]};
let state=structuredClone(defaults),user=null,householdId='',inviteCode='',unsub=null,saveTimer=null,remote=false,currentView='home',marketFilter='pending',pantryFilter='all',marketSearch='';
function migrate(v={}){const x={...structuredClone(defaults),...v};for(const k of ['shopping','tasks','expenses','notes','pantry','events','fixedExpenses','extraIncomes','customCatalog','favorites','priceHistory'])if(!Array.isArray(x[k]))x[k]=[];return x}
function localLoad(){try{return migrate(JSON.parse(localStorage.getItem('nuestroEspacioPro')||'{}'))}catch{return migrate()}}state=localLoad();
function persist(){localStorage.setItem('nuestroEspacioPro',JSON.stringify(state));render();if(user&&householdId&&!remote){clearTimeout(saveTimer);saveTimer=setTimeout(push,500)}}
function stateRef(){return doc(db,'households',householdId,'appState','main')}async function push(){try{sync('saving');await setDoc(stateRef(),{state,updatedAt:serverTimestamp(),updatedBy:user.uid,version:VERSION},{merge:true});sync('ok')}catch(e){console.error(e);sync('error')}}
function sync(mode){$('syncDot').style.background=mode==='error'?'var(--red)':mode==='saving'?'var(--orange)':'var(--green)'}
function toast(t){const e=$('toast');e.textContent=t;e.classList.add('show');clearTimeout(e.t);e.t=setTimeout(()=>e.classList.remove('show'),2200)}
function show(el,on=true){el.hidden=!on}function setLoading(t){$('loadingText').textContent=t;show($('loading'),true);show($('auth'),false);show($('setup'),false);show($('app'),false)}
function openApp(){show($('loading'),false);show($('auth'),false);show($('setup'),false);show($('app'),true);applyTheme();render()}
function stateEmpty(s){return !s.shopping.length&&!s.tasks.length&&!s.expenses.length&&!s.pantry.length&&!s.notes.length}
async function connect(profile){
  householdId=profile.householdId;inviteCode=profile.inviteCode||'';setLoading('Cargando datos compartidos…');if(unsub)unsub();let first=true,opened=false;
  const rescue=setTimeout(()=>{if(!opened){state=localLoad();openApp();sync('error');toast('La nube está tardando. Mostramos tu copia local.')}},12000);
  unsub=onSnapshot(stateRef(),{includeMetadataChanges:true},async snap=>{
    try{
      if(snap.exists()&&snap.data().state){remote=true;state=migrate(snap.data().state);remote=false;localStorage.setItem('nuestroEspacioPro',JSON.stringify(state));}
      else if(first){const local=localLoad();state=local;if(!stateEmpty(local))await push();else await setDoc(stateRef(),{state,version:VERSION,updatedAt:serverTimestamp()});}
      first=false;opened=true;clearTimeout(rescue);openApp();sync(snap.metadata.hasPendingWrites?'saving':'ok');
    }catch(e){console.error('Error procesando datos del hogar',e);opened=true;clearTimeout(rescue);state=localLoad();openApp();sync('error');toast('Abrimos tu copia local; tus datos siguen seguros')}
  },error=>{
    console.error('Error escuchando Firestore',error);opened=true;clearTimeout(rescue);state=localLoad();openApp();sync('error');toast('Sin conexión a Firebase. Usando datos locales.')
  });
}
async function authenticated(u){
  user=u;setLoading('Buscando tu hogar…');
  try{
    const p=await Promise.race([
      getDoc(doc(db,'users',u.uid)),
      new Promise((_,reject)=>setTimeout(()=>reject(new Error('Tiempo de espera agotado al consultar el perfil')),12000))
    ]);
    if(p.exists()&&p.data().householdId)return connect(p.data());
    show($('loading'),false);show($('setup'),true);show($('auth'),false);
  }catch(error){
    console.error('No se pudo cargar el perfil Firebase',error);
    state=localLoad();openApp();sync('error');
    toast('Firebase tardó demasiado. Abrimos tu copia local.');
  }
}
onAuthStateChanged(auth,u=>{
  if(u) authenticated(u).catch(error=>{console.error(error);state=localLoad();openApp();sync('error')});
  else {show($('loading'),false);show($('auth'),true);show($('setup'),false);show($('app'),false)}
},error=>{
  console.error('Error de Authentication',error);show($('loading'),false);show($('auth'),true);$('authError').textContent='No se pudo conectar con Firebase. Revisa internet y vuelve a intentar.';
});
$('loginForm').onsubmit=async e=>{e.preventDefault();try{const f=new FormData(e.currentTarget);await signInWithEmailAndPassword(auth,f.get('email'),f.get('password'))}catch(err){$('authError').textContent=err.message}};$('showRegister').onclick=()=>{show($('loginForm'),false);show($('showRegister'),false);show($('registerForm'),true)};$('backLogin').onclick=()=>{show($('loginForm'),true);show($('showRegister'),true);show($('registerForm'),false)};$('registerForm').onsubmit=async e=>{e.preventDefault();try{const f=new FormData(e.currentTarget),r=await createUserWithEmailAndPassword(auth,f.get('email'),f.get('password'));await updateProfile(r.user,{displayName:f.get('name')})}catch(err){$('authError').textContent=err.message}};
$('createHome').onsubmit=async e=>{e.preventDefault();const name=new FormData(e.currentTarget).get('name'),hid=uid(),code=Math.random().toString(36).slice(2,8).toUpperCase(),b=writeBatch(db);b.set(doc(db,'households',hid),{name,createdBy:user.uid,createdAt:serverTimestamp(),inviteCode:code});b.set(doc(db,'households',hid,'members',user.uid),{name:user.displayName||user.email,email:user.email,role:'owner'});b.set(doc(db,'invites',code),{householdId:hid,status:'active',createdBy:user.uid,uses:0});b.set(doc(db,'users',user.uid),{name:user.displayName||user.email,email:user.email,householdId:hid,inviteCode:code},{merge:true});await b.commit();connect({householdId:hid,inviteCode:code})};
$('joinHome').onsubmit=async e=>{e.preventDefault();const code=String(new FormData(e.currentTarget).get('code')).toUpperCase(),i=await getDoc(doc(db,'invites',code));if(!i.exists())return toast('Código no válido');const d=i.data(),b=writeBatch(db);b.set(doc(db,'households',d.householdId,'members',user.uid),{name:user.displayName||user.email,email:user.email,role:'member'});b.set(doc(db,'users',user.uid),{name:user.displayName||user.email,email:user.email,householdId:d.householdId,inviteCode:code},{merge:true});b.update(doc(db,'invites',code),{uses:increment(1)});await b.commit();connect({householdId:d.householdId,inviteCode:code})};
function catalog(){const map=new Map(CATALOG.map(x=>[x.id,x]));state.customCatalog.forEach(x=>map.set(x.id,x));return [...map.values()]}
function price(x){const p=catalog().find(p=>p.id===x.productId);return num(x.unitPrice)||(p?num(p[state.preferredStore]):0)}function pendingMarket(){return state.shopping.filter(x=>!x.done).reduce((s,x)=>s+num(x.qty)*price(x),0)}function monthExpenses(){const ym=today().slice(0,7);return state.expenses.filter(x=>String(x.date||'').startsWith(ym)).reduce((s,x)=>s+num(x.amount),0)}function fixedTotal(){return state.fixedExpenses.filter(x=>x.active!==false).reduce((s,x)=>s+num(x.amount),0)}function incomeTotal(){return state.salaryPayments.filter(x=>x.active!==false).reduce((s,x)=>s+num(x.amount),0)+state.extraIncomes.filter(x=>String(x.date||'').startsWith(today().slice(0,7))).reduce((s,x)=>s+num(x.amount),0)}
function safe(module,fn){try{return fn()}catch(e){console.error(module,e);return `<div class="card error-card"><h3>No se pudo mostrar ${module}</h3><p class="muted">Tus datos siguen seguros.</p><button class="primary" onclick="location.reload()">Reintentar</button></div>`}}
const titles={home:'Mi Hogar',market:'Mercado',pantry:'Despensa',agenda:'Agenda',more:'Más'};function go(v){currentView=v;$('pageTitle').textContent=titles[v];document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===v));render()}$('nav').onclick=e=>{const b=e.target.closest('button[data-view]');if(b)go(b.dataset.view)};
function render(){if(!$('app')||$('app').hidden)return;$('view').innerHTML=safe(currentView,()=>({home:homeView,market:marketView,pantry:pantryView,agenda:agendaView,more:moreView}[currentView])());bindView()}
function homeView(){const market= pendingMarket(),available=incomeTotal()-fixedTotal()-monthExpenses()-market,low=state.pantry.filter(x=>num(x.qty)<=num(x.minQty)).length;return `<section class="hero"><small>MARGEN ESTIMADO DEL MES</small><strong>${money(available)}</strong><span>${available>=0?'Compromisos cubiertos':'Falta por cubrir'}</span></section><div class="grid"><button class="card metric" data-go="market"><small>Mercado</small><b>${state.shopping.filter(x=>!x.done).length}</b><span class="muted">pendientes</span></button><button class="card metric" data-go="pantry"><small>Despensa</small><b>${low}</b><span class="muted">por reponer</span></button><div class="card metric"><small>Tareas</small><b>${state.tasks.filter(x=>!x.done).length}</b><span class="muted">pendientes</span></div><div class="card metric"><small>Gasto del mes</small><b>${money(monthExpenses())}</b></div></div><div class="section-head"><h2>Atención hoy</h2></div><div class="list">${state.pantry.filter(x=>num(x.qty)<=num(x.minQty)).slice(0,3).map(pantryCard).join('')||'<div class="card empty">Todo en orden en la despensa.</div>'}</div>`}
function marketView(){let a=state.shopping.filter(x=>marketFilter==='all'||marketFilter==='done'?x.done:marketFilter==='pending'?!x.done:state.favorites.includes(x.productId));if(marketSearch)a=a.filter(x=>norm(x.title).includes(norm(marketSearch)));return `<div class="hero"><small>PRESUPUESTO</small><strong>${money(state.budget)}</strong><span>Estimado ${money(pendingMarket())}</span></div><div class="segments" id="storeSeg"><button data-store="market" class="${state.preferredStore==='market'?'active':''}">Mercado</button><button data-store="supermarket" class="${state.preferredStore==='supermarket'?'active':''}">Supermercado</button><button data-store="wholesale" class="${state.preferredStore==='wholesale'?'active':''}">Mayorista</button></div><div class="search">⌕<input id="marketSearch" value="${marketSearch}" placeholder="Buscar en tu lista"></div><div class="segments" id="marketFilters"><button data-filter="pending" class="${marketFilter==='pending'?'active':''}">Pendientes</button><button data-filter="favorites" class="${marketFilter==='favorites'?'active':''}">Favoritos</button><button data-filter="done" class="${marketFilter==='done'?'active':''}">Comprados</button><button data-filter="all" class="${marketFilter==='all'?'active':''}">Todos</button></div><div class="list">${a.map(marketCard).join('')||'<div class="card empty">No hay productos en este filtro.</div>'}</div>`}
function marketCard(x){return `<div class="row-card"><button class="check ${x.done?'done':''}" data-toggle-shop="${x.id}">${x.done?'✓':''}</button><div class="main"><h3>${x.title}</h3><p>${x.qty} ${x.unit} · ${money(num(x.qty)*price(x))}</p></div><button class="pill-btn" data-edit-shop="${x.id}">•••</button></div>`}
function pantryView(){const q=window.__pantryQ||'',a=state.pantry.filter(x=>(!q||norm(x.name).includes(norm(q)))&&(pantryFilter==='all'||pantryFilter==='low'&&num(x.qty)<=num(x.minQty)||pantryFilter==='stock'&&num(x.qty)>num(x.minQty)));return `<div class="section-head"><div><h2>Despensa</h2><p class="muted">Existencias, consumo y reposición.</p></div><button class="pill-btn" data-new-pantry>＋ Producto</button></div><div class="kpis"><div class="kpi"><small>Productos</small><b>${state.pantry.length}</b></div><div class="kpi"><small>Por reponer</small><b>${state.pantry.filter(x=>num(x.qty)<=num(x.minQty)).length}</b></div><div class="kpi"><small>Vence pronto</small><b>${state.pantry.filter(x=>x.expiry&&((new Date(x.expiry)-new Date())/86400000)<=7).length}</b></div></div><div class="search">⌕<input id="pantrySearch" value="${q}" placeholder="Buscar en la despensa"></div><div class="segments" id="pantryFilters"><button data-filter="all" class="${pantryFilter==='all'?'active':''}">Todos</button><button data-filter="low" class="${pantryFilter==='low'?'active':''}">Por reponer</button><button data-filter="stock" class="${pantryFilter==='stock'?'active':''}">En stock</button></div><div class="list">${a.map(pantryCard).join('')||'<div class="card empty">No hay productos para mostrar.</div>'}</div>`}
function pantryCard(x){const max=Math.max(num(x.minQty)*2,1),pct=Math.min(100,num(x.qty)/max*100),low=num(x.qty)<=num(x.minQty),days=num(x.dailyUse)>0?Math.floor(num(x.qty)/num(x.dailyUse)):null;return `<div class="card"><div class="row-card" style="border:0;padding:0;box-shadow:none"><div class="icon">🥫</div><div class="main"><h3>${x.name}</h3><p>${x.qty} ${x.pantryUnit||x.unit||'unidad'} · mínimo ${x.minQty||0}</p></div><button class="pill-btn" data-edit-pantry="${x.id}">Editar</button></div><div class="bar ${low?'low':''}"><span style="width:${pct}%"></span></div><p class="muted">${days!==null?`Dura aprox. ${days} días`:(low?'Requiere reposición':'Stock suficiente')}</p><div class="actions"><button data-consume="${x.id}">Consumir</button><button data-restock="${x.id}">Comprar</button></div></div>`}
function agendaView(){const a=[...state.events].sort((x,y)=>String(x.date).localeCompare(String(y.date)));return `<div class="section-head"><div><h2>Agenda</h2><p class="muted">Pagos, citas y compromisos.</p></div><button class="pill-btn" data-new-event>＋ Evento</button></div><div class="list">${a.map(x=>`<div class="row-card"><div class="icon">📅</div><div class="main"><h3>${x.title}</h3><p>${x.date||'Sin fecha'} ${x.time||''}</p></div><button class="pill-btn danger" data-delete-event="${x.id}">Eliminar</button></div>`).join('')||'<div class="card empty">No tienes eventos próximos.</div>'}</div>`}
function moreView(){return `<div class="list"><button class="row-card" data-open="tasks"><div class="icon">✓</div><div class="main"><h3>Tareas</h3><p>${state.tasks.length} registradas</p></div></button><button class="row-card" data-open="finance"><div class="icon">S/</div><div class="main"><h3>Finanzas</h3><p>Ingresos, gastos y presupuesto</p></div></button><button class="row-card" data-open="account"><div class="icon">☁</div><div class="main"><h3>Cuenta y sincronización</h3><p>Código ${inviteCode||'—'}</p></div></button><button class="row-card" data-open="backup"><div class="icon">⇩</div><div class="main"><h3>Exportar respaldo</h3><p>Copia JSON de tus datos</p></div></button><div class="card"><small>VERSIÓN ACTUAL</small><h2>v${VERSION}</h2><p class="muted">Nueva arquitectura modular · Firebase compatible</p></div></div>`}
function bindView(){document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));$('marketSearch')?.addEventListener('input',e=>{marketSearch=e.target.value;render()});$('marketFilters')?.addEventListener('click',e=>{const b=e.target.closest('button');if(b){marketFilter=b.dataset.filter;render()}});$('storeSeg')?.addEventListener('click',e=>{const b=e.target.closest('button');if(b){state.preferredStore=b.dataset.store;persist()}});$('pantrySearch')?.addEventListener('input',e=>{window.__pantryQ=e.target.value;render()});$('pantryFilters')?.addEventListener('click',e=>{const b=e.target.closest('button');if(b){pantryFilter=b.dataset.filter;render()}});document.querySelectorAll('[data-toggle-shop]').forEach(b=>b.onclick=()=>toggleShop(b.dataset.toggleShop));document.querySelectorAll('[data-edit-shop]').forEach(b=>b.onclick=()=>shopForm(b.dataset.editShop));document.querySelectorAll('[data-new-pantry]').forEach(b=>b.onclick=()=>pantryForm());document.querySelectorAll('[data-edit-pantry]').forEach(b=>b.onclick=()=>pantryForm(b.dataset.editPantry));document.querySelectorAll('[data-consume]').forEach(b=>b.onclick=()=>consumeForm(b.dataset.consume));document.querySelectorAll('[data-restock]').forEach(b=>b.onclick=()=>restock(b.dataset.restock));document.querySelectorAll('[data-new-event]').forEach(b=>b.onclick=eventForm);document.querySelectorAll('[data-delete-event]').forEach(b=>b.onclick=()=>{state.events=state.events.filter(x=>x.id!==b.dataset.deleteEvent);persist()});document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>moreAction(b.dataset.open))}
function openSheet(title,html){$('sheetTitle').textContent=title;$('sheetBody').innerHTML=html;show($('sheet'),true);document.body.style.overflow='hidden'}function closeSheet(){show($('sheet'),false);document.body.style.overflow=''}$('sheetClose').onclick=closeSheet;$('sheet').onclick=e=>{if(e.target===$('sheet'))closeSheet()};
const units=['kg','g','litro','ml','unidad','unidades','docena','bolsa','paquete','botella','lata','frasco','caja','porciones'];function opts(sel){return units.map(u=>`<option ${u===sel?'selected':''}>${u}</option>`).join('')}
function shopForm(id=''){const x=state.shopping.find(x=>x.id===id)||{id:'',title:'',qty:1,unit:'unidad',unitPrice:0,category:'Otros'};openSheet(id?'Editar compra':'Nueva compra',`<form class="form" id="sf"><input type="hidden" name="id" value="${x.id}"><label>Producto<input name="title" value="${x.title}" required list="catalogNames"></label><datalist id="catalogNames">${catalog().slice(0,400).map(p=>`<option value="${p.name}">`).join('')}</datalist><div class="two"><label>Cantidad<input name="qty" type="number" step=".01" value="${x.qty}" required></label><label>Unidad<select name="unit">${opts(x.unit)}</select></label></div><label>Precio por unidad<input name="unitPrice" type="number" step=".01" value="${price(x)}"></label><button class="primary">Guardar</button>${id?'<button type="button" class="primary danger" id="delShop">Eliminar</button>':''}</form>`);$('sf').onsubmit=e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.currentTarget));o.qty=num(o.qty);o.unitPrice=num(o.unitPrice);const p=catalog().find(p=>norm(p.name)===norm(o.title));o.productId=p?.id||x.productId||'';o.done=x.done||false;if(id)Object.assign(x,o);else{ o.id=uid();state.shopping.unshift(o)}closeSheet();persist()};$('delShop')?.addEventListener('click',()=>{state.shopping=state.shopping.filter(v=>v.id!==id);closeSheet();persist()})}
function toggleShop(id){const x=state.shopping.find(x=>x.id===id);if(!x)return;if(!x.done)return completePurchase(x);rollbackPurchase(x);persist()}
function completePurchase(x){openSheet('Confirmar compra',`<form class="form" id="complete"><p>${x.title} · ${x.qty} ${x.unit}</p><label>Total pagado<input name="amount" type="number" step=".01" value="${(x.qty*price(x)).toFixed(2)}"></label><label>Cantidad a despensa<input name="pantryQty" type="number" step=".01" value="${x.qty}"></label><label>Unidad de despensa<select name="pantryUnit">${opts(x.pantryUnit||x.unit)}</select></label><button class="primary">Guardar compra</button></form>`);$('complete').onsubmit=e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.currentTarget)),eid=uid();x.done=true;x.actualTotal=num(o.amount);x.purchaseDate=today();x.linkedExpenseId=eid;x.pantryAddQty=num(o.pantryQty);x.pantryUnit=o.pantryUnit;state.expenses.unshift({id:eid,sourcePurchaseId:x.id,title:'Mercado: '+x.title,amount:x.actualTotal,date:today(),category:'Mercado'});let p=state.pantry.find(p=>norm(p.name)===norm(x.title));if(!p){p={id:uid(),name:x.title,qty:0,minQty:0,unit:x.pantryUnit,pantryUnit:x.pantryUnit,purchaseUnit:x.unit,conversionRate:x.qty?x.pantryAddQty/x.qty:1};state.pantry.unshift(p)}p.qty=num(p.qty)+x.pantryAddQty;x.pantryMovement={itemId:p.id,qty:x.pantryAddQty};closeSheet();persist()}}
function rollbackPurchase(x){x.done=false;if(x.linkedExpenseId)state.expenses=state.expenses.filter(e=>e.id!==x.linkedExpenseId);if(x.pantryMovement){const p=state.pantry.find(p=>p.id===x.pantryMovement.itemId);if(p)p.qty=Math.max(0,num(p.qty)-num(x.pantryMovement.qty))}delete x.linkedExpenseId;delete x.pantryMovement}
function pantryForm(id=''){const x=state.pantry.find(x=>x.id===id)||{name:'',qty:0,minQty:0,unit:'unidad',pantryUnit:'unidad',purchaseUnit:'unidad',conversionRate:1,dailyUse:0,expiry:''};openSheet(id?'Editar producto':'Nuevo producto',`<form class="form" id="pf"><label>Producto<input name="name" value="${x.name}" required></label><div class="two"><label>Cantidad<input name="qty" type="number" step=".01" value="${x.qty}"></label><label>Mínimo<input name="minQty" type="number" step=".01" value="${x.minQty}"></label></div><div class="two"><label>Unidad de despensa<select name="pantryUnit">${opts(x.pantryUnit||x.unit)}</select></label><label>Unidad de compra<select name="purchaseUnit">${opts(x.purchaseUnit||x.unit)}</select></label></div><div class="two"><label>Unidades por compra<input name="conversionRate" type="number" step=".01" value="${x.conversionRate||1}"></label><label>Consumo diario<input name="dailyUse" type="number" step=".01" value="${x.dailyUse||0}"></label></div><label>Vencimiento<input name="expiry" type="date" value="${x.expiry||''}"></label><button class="primary">Guardar</button>${id?'<button type="button" class="primary danger" id="delPantry">Eliminar</button>':''}</form>`);$('pf').onsubmit=e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.currentTarget));['qty','minQty','conversionRate','dailyUse'].forEach(k=>o[k]=num(o[k]));o.unit=o.pantryUnit;if(id)Object.assign(x,o);else{ o.id=uid();state.pantry.unshift(o)}closeSheet();persist()};$('delPantry')?.addEventListener('click',()=>{state.pantry=state.pantry.filter(v=>v.id!==id);closeSheet();persist()})}
function consumeForm(id){const x=state.pantry.find(x=>x.id===id);openSheet('Consumir '+x.name,`<form class="form" id="cf"><p>Disponible: <b>${x.qty} ${x.pantryUnit||x.unit}</b></p><label>Cantidad<input name="qty" type="number" step=".01" required></label><label>Unidad<select name="unit">${opts(x.pantryUnit||x.unit)}</select></label><button class="primary">Confirmar consumo</button></form>`);$('cf').onsubmit=e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.currentTarget));let q=num(o.qty),base=x.pantryUnit||x.unit;if(base==='kg'&&o.unit==='g')q/=1000;if(base==='litro'&&o.unit==='ml')q/=1000;if(q>x.qty)return toast('No hay suficiente stock');x.qty=Math.max(0,x.qty-q);closeSheet();persist()}}
function restock(id){const x=state.pantry.find(x=>x.id===id),need=Math.max(0,num(x.minQty)-num(x.qty));if(!need)return toast('Stock suficiente');const qty=need/(num(x.conversionRate)||1),e=state.shopping.find(s=>!s.done&&norm(s.title)===norm(x.name));if(e)e.qty+=qty;else state.shopping.unshift({id:uid(),title:x.name,qty,unit:x.purchaseUnit||x.unit,productId:'',unitPrice:0,done:false});persist();toast('Añadido al mercado')}
function eventForm(){openSheet('Nuevo evento',`<form class="form" id="ef"><label>Título<input name="title" required></label><div class="two"><label>Fecha<input name="date" type="date" value="${today()}"></label><label>Hora<input name="time" type="time"></label></div><button class="primary">Guardar</button></form>`);$('ef').onsubmit=e=>{e.preventDefault();state.events.unshift({id:uid(),...Object.fromEntries(new FormData(e.currentTarget))});closeSheet();persist()}}
function moreAction(a){if(a==='backup'){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),u=URL.createObjectURL(blob),l=document.createElement('a');l.href=u;l.download='nuestro-espacio-v7.json';l.click();URL.revokeObjectURL(u);return}if(a==='account'){openSheet('Cuenta y sincronización',`<div class="list"><div class="card"><small>USUARIO</small><h3>${user?.displayName||user?.email}</h3></div><div class="card"><small>CÓDIGO DEL HOGAR</small><h2>${inviteCode||'—'}</h2><button class="primary" id="copyCode">Copiar código</button></div><button class="primary danger" id="logout">Cerrar sesión</button></div>`);$('copyCode').onclick=()=>navigator.clipboard.writeText(inviteCode).then(()=>toast('Código copiado'));$('logout').onclick=()=>signOut(auth).then(closeSheet);return}if(a==='finance'){openSheet('Finanzas',`<div class="grid"><div class="card metric"><small>Ingresos</small><b>${money(incomeTotal())}</b></div><div class="card metric"><small>Fijos</small><b>${money(fixedTotal())}</b></div><div class="card metric"><small>Mercado</small><b>${money(pendingMarket())}</b></div><div class="card metric"><small>Gastos</small><b>${money(monthExpenses())}</b></div></div>`);return}if(a==='tasks'){openSheet('Tareas',`<form class="form" id="tf"><label>Nueva tarea<input name="title" required></label><button class="primary">Agregar</button></form><div class="list" id="taskList">${state.tasks.map(t=>`<div class="row-card"><button class="check ${t.done?'done':''}" data-task="${t.id}">${t.done?'✓':''}</button><div class="main"><h3>${t.title}</h3></div></div>`).join('')}</div>`);$('tf').onsubmit=e=>{e.preventDefault();state.tasks.unshift({id:uid(),title:new FormData(e.currentTarget).get('title'),done:false});closeSheet();persist()};document.querySelectorAll('[data-task]').forEach(b=>b.onclick=()=>{const t=state.tasks.find(t=>t.id===b.dataset.task);t.done=!t.done;closeSheet();persist()})}}
$('fab').onclick=()=>currentView==='market'?shopForm():currentView==='pantry'?pantryForm():currentView==='agenda'?eventForm():moreAction('tasks');$('themeBtn').onclick=()=>{state.theme=state.theme==='dark'?'light':'dark';applyTheme();persist()};function applyTheme(){document.body.classList.toggle('dark',state.theme==='dark')}$('syncBtn').onclick=push;
window.addEventListener('error',event=>{console.error('Error global',event.error||event.message);if(!$('loading').hidden){state=localLoad();openApp();sync('error');toast('Se recuperó el inicio de la app.')}});
window.addEventListener('unhandledrejection',event=>{console.error('Promesa no controlada',event.reason);if(!$('loading').hidden){state=localLoad();openApp();sync('error');toast('Se recuperó el inicio de la app.')}});
setTimeout(()=>{if(!$('loading').hidden){state=localLoad();openApp();sync('error');toast('Inicio recuperado con la copia local.')}},15000);
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');
