
(()=>{
 const VERSION_DUAL='5.8.0';
 const norm=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
 const num=v=>Number(v||0);
 const ROUND=(v,step)=>{step=num(step)||.5;return Math.ceil((num(v)-1e-9)/step)*step};
 const DEFAULTS={
  'papa':{purchaseUnit:'kg',pantryUnit:'unidades',conversionRate:6,purchaseStep:.5},'papa blanca':{purchaseUnit:'kg',pantryUnit:'unidades',conversionRate:6,purchaseStep:.5},'papa amarilla':{purchaseUnit:'kg',pantryUnit:'unidades',conversionRate:8,purchaseStep:.5},
  'tomate':{purchaseUnit:'kg',pantryUnit:'unidades',conversionRate:6,purchaseStep:.5},'cebolla':{purchaseUnit:'kg',pantryUnit:'unidades',conversionRate:5,purchaseStep:.5},'cebolla roja':{purchaseUnit:'kg',pantryUnit:'unidades',conversionRate:5,purchaseStep:.5},
  'limon':{purchaseUnit:'kg',pantryUnit:'unidades',conversionRate:20,purchaseStep:.25},'manzana':{purchaseUnit:'kg',pantryUnit:'unidades',conversionRate:6,purchaseStep:.5},'platano':{purchaseUnit:'kg',pantryUnit:'unidades',conversionRate:7,purchaseStep:.5},
  'naranja':{purchaseUnit:'kg',pantryUnit:'unidades',conversionRate:6,purchaseStep:.5},'mandarina':{purchaseUnit:'kg',pantryUnit:'unidades',conversionRate:8,purchaseStep:.5},'palta':{purchaseUnit:'kg',pantryUnit:'unidades',conversionRate:4,purchaseStep:.5},
  'zanahoria':{purchaseUnit:'kg',pantryUnit:'unidades',conversionRate:7,purchaseStep:.5},'camote':{purchaseUnit:'kg',pantryUnit:'unidades',conversionRate:5,purchaseStep:.5},'ajo':{purchaseUnit:'kg',pantryUnit:'cabezas',conversionRate:12,purchaseStep:.25},
  'huevo':{purchaseUnit:'docena',pantryUnit:'unidades',conversionRate:12,purchaseStep:1},'huevos':{purchaseUnit:'docena',pantryUnit:'unidades',conversionRate:12,purchaseStep:1},'pollo':{purchaseUnit:'kg',pantryUnit:'porciones',conversionRate:4,purchaseStep:.5},'carne':{purchaseUnit:'kg',pantryUnit:'porciones',conversionRate:5,purchaseStep:.25}
 };
 function defaultsFor(name,purchaseUnit){const key=norm(name);let d=DEFAULTS[key]||Object.entries(DEFAULTS).find(([k])=>key.includes(k))?.[1];if(d)return {...d};if(norm(purchaseUnit)==='kg')return {purchaseUnit:'kg',pantryUnit:'unidades',conversionRate:1,purchaseStep:.5};return {purchaseUnit:purchaseUnit||'unidad',pantryUnit:purchaseUnit||'unidad',conversionRate:1,purchaseStep:1}}
 function configForProduct(x){const pantry=(data.pantry||[]).find(p=>(x.productId&&p.productId===x.productId)||norm(p.name)===norm(x.title));const base=defaultsFor(x.title,x.unit);return {purchaseUnit:pantry?.purchaseUnit||x.purchaseUnit||base.purchaseUnit||x.unit,pantryUnit:pantry?.pantryUnit||pantry?.unit||x.pantryUnit||base.pantryUnit,conversionRate:num(pantry?.conversionRate||x.conversionRate||base.conversionRate)||1,purchaseStep:num(pantry?.purchaseStep||x.purchaseStep||base.purchaseStep)||.5}}
 function purchaseFields(){return {mode:purchaseForm.elements.inventoryMode,unit:purchaseForm.elements.pantryUnit,rate:purchaseForm.elements.conversionRate,actual:purchaseForm.elements.actualPantryQty,box:document.getElementById('purchaseConversionFields'),eq:document.getElementById('purchaseConversionEquation')}}
 function refreshPurchaseConversion(){const x=data.shopping.find(v=>v.id===purchaseForm.id.value);if(!x)return;const f=purchaseFields(),convert=f.mode.value==='convert';f.box.hidden=!convert;if(!convert){f.actual.value=x.qty;return}const rate=num(f.rate.value)||1,suggest=num(x.qty)*rate;f.actual.value=String(Math.round(suggest*100)/100);f.eq.textContent=`1 ${x.unit||'unidad'} ≈ ${rate} ${f.unit.value||'unidades'} · ${x.qty} ${x.unit||''} → ${Math.round(suggest*100)/100} ${f.unit.value||'unidades'}`}
 const baseOpenPurchase=window.openPurchase;
 window.openPurchase=function(id){baseOpenPurchase(id);const x=data.shopping.find(v=>v.id===id);if(!x)return;const c=configForProduct(x),f=purchaseFields(),different=norm(c.purchaseUnit)!==norm(c.pantryUnit)||c.conversionRate!==1;f.mode.value=different?'convert':'same';f.unit.value=c.pantryUnit;f.rate.value=c.conversionRate;refreshPurchaseConversion()};
 ['change','input'].forEach(ev=>{purchaseForm.elements.inventoryMode?.addEventListener(ev,refreshPurchaseConversion);purchaseForm.elements.pantryUnit?.addEventListener(ev,refreshPurchaseConversion);purchaseForm.elements.conversionRate?.addEventListener(ev,refreshPurchaseConversion)});
 function applyDualPurchaseToPantry(x){
  const pantryQty=num(x.pantryAddQty||x.qty);if(!(pantryQty>0))return;
  let item=pantryMatchForPurchase(x),created=false;
  if(!item){item={id:uid(),productId:x.productId||'',name:x.title,qty:0,minQty:0,unit:x.pantryUnit||x.unit||'unidad',pantryUnit:x.pantryUnit||x.unit||'unidad',purchaseUnit:x.purchaseUnit||x.unit||'unidad',conversionRate:num(x.conversionRate)||1,purchaseStep:num(x.purchaseStep)||.5,expiry:'',createdFromPurchase:true};data.pantry.unshift(item);created=true}
  item.qty=num(item.qty)+pantryQty;item.unit=x.pantryUnit||item.pantryUnit||item.unit;item.pantryUnit=item.unit;item.purchaseUnit=x.purchaseUnit||x.unit||item.purchaseUnit||item.unit;item.conversionRate=num(x.conversionRate)||num(item.conversionRate)||1;item.purchaseStep=num(x.purchaseStep)||num(item.purchaseStep)||.5;
  x.pantryMovement={itemId:item.id,qty:pantryQty,created,unit:item.unit};
 }
 applyPurchaseToPantry=applyDualPurchaseToPantry;
 purchaseForm.onsubmit=e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target)),x=data.shopping.find(v=>v.id===o.id);if(!x)return;rollbackCompletedPurchase(x);const est=num(x.qty)*currentUnitPrice(x),actual=num(o.actualTotal),historyId=uid(),expenseId=uid(),cfg=configForProduct(x),convert=o.inventoryMode==='convert';x.purchaseUnit=x.unit;x.pantryUnit=convert?(o.pantryUnit||cfg.pantryUnit):x.unit;x.conversionRate=convert?(num(o.conversionRate)||cfg.conversionRate):1;x.purchaseStep=cfg.purchaseStep;x.pantryAddQty=convert?(num(o.actualPantryQty)||num(x.qty)*x.conversionRate):num(x.qty);x.done=true;x.actualTotal=actual;x.purchaseDate=o.date;x.purchasePlace=o.place;x.linkedExpenseId=expenseId;x.linkedPriceHistoryId=historyId;data.priceHistory.unshift({id:historyId,sourcePurchaseId:x.id,productId:x.productId,title:x.title,qty:num(x.qty),unit:x.unit,pantryQty:x.pantryAddQty,pantryUnit:x.pantryUnit,conversionRate:x.conversionRate,store:x.store||data.preferredStore,estimatedTotal:est,actualTotal:actual,unitActual:num(x.qty)>0?actual/num(x.qty):actual,place:o.place,date:o.date});data.expenses.unshift({id:expenseId,sourcePurchaseId:x.id,title:'Mercado: '+x.title,amount:actual,date:o.date,paidBy:x.assigned||'Ambos',category:'Mercado'});applyDualPurchaseToPantry(x);closeModal('purchaseModal');save();toast(`Compra guardada · +${x.pantryAddQty} ${x.pantryUnit} en despensa`)};
 // Pantry form configuration
 const baseOpenPantry=window.openPantryForm;
 window.openPantryForm=function(id=''){baseOpenPantry(id);const x=(data.pantry||[]).find(v=>v.id===id),base=defaultsFor(x?.name,x?.purchaseUnit||x?.unit);const f=pantryForm.elements;f.purchaseUnit.value=x?.purchaseUnit||base.purchaseUnit||x?.unit||'unidad';f.pantryUnit.value=x?.pantryUnit||x?.unit||base.pantryUnit||'unidad';f.conversionRate.value=x?.conversionRate||base.conversionRate||1;f.purchaseStep.value=x?.purchaseStep||base.purchaseStep||.5;f.unit.value=f.pantryUnit.value;refreshPantryEquation()};
 function refreshPantryEquation(){const f=pantryForm.elements,rate=num(f.conversionRate.value),pu=f.purchaseUnit.value||'unidad',iu=f.pantryUnit.value||f.unit.value||'unidad';document.getElementById('pantryConversionEquation').textContent=rate?`1 ${pu} ≈ ${rate} ${iu}`:'Sin conversión configurada';f.unit.value=iu}
 ['input','change'].forEach(ev=>['purchaseUnit','pantryUnit','conversionRate'].forEach(n=>pantryForm.elements[n]?.addEventListener(ev,refreshPantryEquation)));
 pantryForm.onsubmit=e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target));o.qty=num(o.qty);o.minQty=num(o.minQty);o.dailyUse=num(o.dailyUse);o.conversionRate=num(o.conversionRate)||1;o.purchaseStep=num(o.purchaseStep)||.5;o.pantryUnit=o.pantryUnit||o.unit||'unidad';o.unit=o.pantryUnit;o.purchaseUnit=o.purchaseUnit||o.unit;const x=data.pantry.find(v=>v.id===o.id);if(x)Object.assign(x,o);else{o.id=uid();data.pantry.push(o)}closeModal('pantryFormModal');save();renderPantryPage();renderPantryHomeVisual();toast('Despensa y conversión actualizadas')};
 // Inverse conversion for restocking
 window.addPantryToMarket=function(id){const x=(data.pantry||[]).find(v=>v.id===id);if(!x)return;const target=Math.max(num(x.minQty),1),needInventory=Math.max(0,target-num(x.qty));if(needInventory<=0){toast('Este producto aún tiene stock suficiente');return}const rate=num(x.conversionRate)||1,step=num(x.purchaseStep)||.5,purchaseQty=ROUND(needInventory/rate,step),purchaseUnit=x.purchaseUnit||x.unit||'unidad',name=String(x.name||'Producto'),existing=(data.shopping||[]).find(s=>!s.done&&norm(s.title)===norm(name));if(existing){if(norm(existing.unit)===norm(purchaseUnit))existing.qty=num(existing.qty)+purchaseQty;else{existing.qty=purchaseQty;existing.unit=purchaseUnit}}else{let p=(typeof catalog==='function'?catalog():[]).find(p=>norm(p.name)===norm(name));data.shopping.unshift({id:uid(),productId:p?.id||x.productId||'',title:name,qty:purchaseQty,unit:purchaseUnit,purchaseUnit,pantryUnit:x.pantryUnit||x.unit,conversionRate:rate,purchaseStep:step,unitPrice:p?p[data.preferredStore]:0,store:data.preferredStore,assigned:'Ambos',category:p?.category||'Despensa',done:false,fromPantry:true})}save();toast(`${name}: comprar aprox. ${purchaseQty} ${purchaseUnit}`);renderPantryPage();renderPantryHomeVisual()};
 // Enhanced pantry cards with dual unit information
 function unitMeta(x){const rate=num(x.conversionRate)||1,pu=x.purchaseUnit||x.unit,iu=x.pantryUnit||x.unit;if(norm(pu)===norm(iu)&&rate===1)return '';return `<div class="pantry-conversion-chip">🛒 1 ${esc(pu)} ≈ ${rate} ${esc(iu)}</div>`}
 function restockMeta(x){const need=Math.max(0,Math.max(num(x.minQty),1)-num(x.qty));if(!need)return '';const rate=num(x.conversionRate)||1,step=num(x.purchaseStep)||.5,qty=ROUND(need/rate,step);return `<div class="restock-suggestion">Faltan <b>${need} ${esc(x.pantryUnit||x.unit)}</b> · compra sugerida <b>${qty} ${esc(x.purchaseUnit||x.unit)}</b></div>`}
 const baseRenderPantryPage=window.renderPantryPage;
 window.renderPantryPage=function(){baseRenderPantryPage();document.querySelectorAll('#pantryPageList .pantry-product').forEach((card,i)=>{const q=String(document.getElementById('pantrySearch')?.value||'').trim().toLowerCase();let a=[...(data.pantry||[])].filter(x=>(!q||String(x.name||'').toLowerCase().includes(q))&&(pantryFilter==='all'||pantryState(x)===pantryFilter));a.sort((x,y)=>({low:0,expiring:1,stock:2}[pantryState(x)]-({low:0,expiring:1,stock:2}[pantryState(y)])));const x=a[i];if(!x)return;const main=card.querySelector('.pantry-product-main');if(main&&!main.querySelector('.pantry-conversion-chip'))main.insertAdjacentHTML('beforeend',unitMeta(x)+restockMeta(x))})};
 const baseItemHTML=window.itemHTML||itemHTML;
 itemHTML=function(x,type){let html=baseItemHTML(x,type);if(type==='shopping'&&x.done&&x.pantryUnit&&norm(x.pantryUnit)!==norm(x.unit)){html=html.replace('</div></div><div class="actions">',`<div class="unit-flow"><strong>${x.qty} ${esc(x.unit)}</strong><span class="unit-arrow">→</span><strong>${x.pantryAddQty} ${esc(x.pantryUnit)} en despensa</strong></div></div></div><div class="actions">`)}return html};
 // Version and migration defaults for existing pantry products
 (data.pantry||[]).forEach(x=>{const d=defaultsFor(x.name,x.purchaseUnit||x.unit);x.pantryUnit=x.pantryUnit||x.unit||d.pantryUnit;x.unit=x.pantryUnit;x.purchaseUnit=x.purchaseUnit||d.purchaseUnit||x.unit;x.conversionRate=num(x.conversionRate)||((norm(x.purchaseUnit)!==norm(x.pantryUnit))?d.conversionRate:1);x.purchaseStep=num(x.purchaseStep)||d.purchaseStep||.5});
 document.querySelectorAll('.version-card small').forEach(x=>x.textContent=x.textContent.replace(/v\d+\.\d+\.\d+/,'v'+VERSION_DUAL));const status=document.getElementById('versionStatus');if(status)status.textContent='Compilación: 13/07/2026 · Doble unidad y reposición inteligente';
 const prevRenderAll=window.renderAll;window.renderAll=function(){prevRenderAll();renderPantryPage();document.querySelectorAll('.version-card small').forEach(x=>x.textContent=x.textContent.replace(/v\d+\.\d+\.\d+/,'v'+VERSION_DUAL))};
 save();renderAll();
})();
