
(()=>{
 const VERSION_58='5.8.0';
 let pantryFilter='all';
 const n=v=>Number(v||0);
 const d0=v=>{const x=new Date(v+'T00:00:00');return isNaN(x)?null:x};
 const daysTo=v=>{const x=d0(v);if(!x)return null;return Math.ceil((x-new Date(new Date().toDateString()))/86400000)};
 function pantryLevel(x){const q=n(x.qty),m=Math.max(.001,n(x.minQty));return Math.max(0,Math.min(100,Math.round(q/(m*2)*100)))}
 function pantryState(x){const q=n(x.qty),m=n(x.minQty),dd=daysTo(x.expiry);if(q<=m)return 'low';if(dd!==null&&dd<=7)return 'expiring';return 'stock'}
 function emojiFor(name=''){const t=String(name).toLowerCase();if(/leche|yogur|queso/.test(t))return'🥛';if(/arroz|azúcar|harina|fideo/.test(t))return'🌾';if(/tomate|verdura|lechuga/.test(t))return'🥬';if(/fruta|manzana|plátano|sandía/.test(t))return'🍎';if(/aceite/.test(t))return'🫗';if(/papel|limpieza|detergente/.test(t))return'🧴';return'📦'}
 window.renderPantryPage=function(){
   const list=document.getElementById('pantryPageList');if(!list)return;
   const q=String(document.getElementById('pantrySearch')?.value||'').trim().toLowerCase();
   const all=[...(data.pantry||[])];
   const low=all.filter(x=>pantryState(x)==='low').length,exp=all.filter(x=>pantryState(x)==='expiring').length;
   document.getElementById('pantryPageKpis').innerHTML=`<div class="pantry-page-kpi"><small>PRODUCTOS</small><b>${all.length}</b></div><div class="pantry-page-kpi"><small>POR REPONER</small><b>${low}</b></div><div class="pantry-page-kpi"><small>VENCE PRONTO</small><b>${exp}</b></div>`;
   let a=all.filter(x=>(!q||String(x.name||'').toLowerCase().includes(q))&&(pantryFilter==='all'||pantryState(x)===pantryFilter));
   a.sort((x,y)=>({low:0,expiring:1,stock:2}[pantryState(x)]-({low:0,expiring:1,stock:2}[pantryState(y)])));
   list.innerHTML=a.map(x=>{const pct=pantryLevel(x),state=pantryState(x),daily=n(x.dailyUse),days=daily>0?Math.floor(n(x.qty)/daily):null,dd=daysTo(x.expiry),label=state==='low'?'Reponer':state==='expiring'?'Vence pronto':'En stock',cls=state==='low'?'low':state==='expiring'?'warn':'',fill=pct<=30?'low':pct<=60?'mid':'';return `<article class="pantry-product"><div class="pantry-product-top"><div class="pantry-product-icon">${emojiFor(x.name)}</div><div class="pantry-product-main"><div class="pantry-product-name"><span>${esc(x.name)}</span><span class="pantry-status ${cls}">${label}</span></div><div class="stock-track"><div class="stock-fill ${fill}" style="width:${pct}%"></div></div><div class="pantry-product-info"><span><b>${n(x.qty)} ${esc(x.unit||'unidad')}</b> · mínimo ${n(x.minQty)}</span><span>${days!==null?`Dura aprox. ${days} días`:dd!==null?`Vence ${dd===0?'hoy':dd>0?`en ${dd} días`:`hace ${Math.abs(dd)} días`}`:'Configura consumo diario'}</span></div></div></div><div class="pantry-actions"><button onclick="consumePantry('${x.id}')">Consumir</button><button onclick="adjustPantry('${x.id}',1);renderPantryPage()">＋ Stock</button><button onclick="openPantryForm('${x.id}')">Editar</button><button class="buy" onclick="addPantryToMarket('${x.id}');renderPantryPage()">Comprar</button></div></article>`}).join('')||'<div class="empty">No hay productos que coincidan con este filtro.</div>';
 };
 window.consumePantry=function(id){const x=(data.pantry||[]).find(v=>v.id===id);if(!x)return;const suggested=n(x.dailyUse)||1;const raw=prompt(`¿Cuánto de ${x.name} consumiste?`,suggested);if(raw===null)return;const amount=n(raw);if(amount<=0)return;x.qty=Math.max(0,n(x.qty)-amount);save();renderPantryPage();if(typeof renderPantryHomeVisual==='function')renderPantryHomeVisual();toast(`${x.name}: stock actualizado`)};
 const oldShow=window.showView;
 window.showView=function(name){if(name==='pantry'){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id==='pantryView'));document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.view==='pantry'));pageTitle.textContent='Despensa';pageSubtitle.textContent='Existencias, consumo y reposición';fab.style.display='block';renderPantryPage();window.scrollTo(0,0);return}if(name==='agenda'){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id==='agendaView'));document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.view==='agenda'));pageTitle.textContent='Agenda';pageSubtitle.textContent='Pagos y compromisos';fab.style.display='none';renderAgendaQuick();window.scrollTo(0,0);return}oldShow(name)};
 function renderAgendaQuick(){const el=document.getElementById('agendaQuickList');if(!el)return;const a=[...(data.events||[])].sort((x,y)=>String(x.date).localeCompare(String(y.date))).filter(x=>!x.date||x.date>=today()).slice(0,12);el.innerHTML=a.length?a.map(x=>`<div class="card"><div class="item"><div class="insight-icon">📅</div><div class="main"><div class="title">${esc(x.title||'Evento')}</div><div class="meta"><span class="agenda-card-date">${esc(x.date||'Sin fecha')}</span>${x.note?`<span>${esc(x.note)}</span>`:''}</div></div></div></div>`).join(''):'<div class="empty">No hay próximos eventos. Abre la agenda para agregar uno.</div>'}
 document.getElementById('pantrySearch')?.addEventListener('input',renderPantryPage);
 document.querySelectorAll('#pantryPageFilters .filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('#pantryPageFilters .filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');pantryFilter=b.dataset.filter;renderPantryPage()});
 // Add moved modules to More
 const more=document.querySelector('#moreView .settings');if(more&&!document.getElementById('movedModules57')){const box=document.createElement('div');box.id='movedModules57';box.innerHTML=`<div class="setting"><div><b>Tareas compartidas</b><small>Pendientes, responsables y fechas</small></div><button class="text-btn" onclick="showView('tasks')">Abrir</button></div><div class="setting"><div><b>Recetas peruanas</b><small>Regiones, ingredientes y menú</small></div><button class="text-btn" onclick="showView('recipes')">Abrir</button></div><div class="setting"><div><b>Estadísticas</b><small>Gastos, categorías e historial</small></div><button class="text-btn" onclick="showView('stats')">Abrir</button></div>`;more.prepend(box)}
 // Compact home pantry and direct navigation
 const oldHomeVisual=window.renderPantryHomeVisual;window.renderPantryHomeVisual=function(){oldHomeVisual?.();const el=document.getElementById('pantryHomeVisual');if(el){el.classList.add('home-pantry-preview');const btn=el.querySelector('.pantry-home-head button');if(btn){btn.textContent='Abrir';btn.onclick=()=>showView('pantry')}}};
 const oldAll=window.renderAll;window.renderAll=function(){oldAll();renderPantryPage();renderAgendaQuick();document.querySelectorAll('.version-card small').forEach(x=>x.textContent=x.textContent.replace(/v\d+\.\d+\.\d+/,'v'+VERSION_58));const st=document.getElementById('versionStatus');if(st)st.textContent='Compilación: 13/07/2026 · Despensa dedicada y navegación renovada'};
 // FAB context
 document.getElementById('fab').addEventListener('click',()=>{const active=document.querySelector('.view.active')?.id;if(active==='pantryView')setTimeout(()=>openPantryForm(),0)},true);
 renderAll();
})();
